<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>False</UseWindowsForms>
    <!-- Adding nullability settings -->
    <!-- <WarningsAsErrors>nullable</WarningsAsErrors> -->

    <!-- Single file publishing settings -->
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <!-- <RuntimeIdentifier>win-x64</RuntimeIdentifier> -->
    <PublishReadyToRun>false</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>embedded</DebugType>

  </PropertyGroup>  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Management" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\AppIcon.ico" />
    <EmbeddedResource Include="Resources\WqlHighlightDark.xshd" />
    <EmbeddedResource Include="Resources\WqlHighlightLight.xshd" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WmiExplorer.PropertyGrid\WmiExplorer.PropertyGrid.csproj" />
  </ItemGroup>

</Project>
